# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/dell/venue3x40-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libIMGegl.so:system/vendor/lib/libIMGegl.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/liboclcompiler.so:system/vendor/lib/liboclcompiler.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libPVROCL.so:system/vendor/lib/libPVROCL.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libsrv_init.so:system/vendor/lib/libsrv_init.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libsrv_um.so:system/vendor/lib/libsrv_um.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libufwriter.so:system/vendor/lib/libufwriter.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libusc.so:system/vendor/lib/libusc.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/egl/libEGL_POWERVR_ROGUE.so:system/vendor/lib/egl/libEGL_POWERVR_ROGUE.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/egl/libGLESv1_CM_POWERVR_ROGUE.so:system/vendor/lib/egl/libGLESv1_CM_POWERVR_ROGUE.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/egl/libGLESv2_POWERVR_ROGUE.so:system/vendor/lib/egl/libGLESv2_POWERVR_ROGUE.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/hw/gralloc.merrifield.so:system/vendor/lib/hw/gralloc.merrifield.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/hw/hwcomposer.merrifield.so:system/vendor/lib/hw/hwcomposer.merrifield.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libhwcwidi.so:system/vendor/lib/libhwcwidi.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libmultidisplay.so:system/vendor/lib/libmultidisplay.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libvpp_setting.so:system/vendor/lib/libvpp_setting.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libcorkscrew.so:system/vendor/lib/libcorkscrew.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libwsbm.so:system/vendor/lib/libwsbm.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libva.so:system/vendor/lib/libva.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libva-android.so:system/vendor/lib/libva-android.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libva-tpi.so:system/vendor/lib/libva-tpi.so \
    vendor/dell/venue3x40-common/proprietary/vendor/firmware/bcmdhd_aob.cal:system/vendor/firmware/bcmdhd_aob.cal
