# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/dell/venue3x40-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/dell/venue3x40-common/proprietary/vendor/bin/gpsd:system/vendor/bin/gpsd \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/hw/gps.saltbay.so:system/vendor/lib/hw/gps.saltbay.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libmmgrcli.so:system/vendor/lib/libmmgrcli.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libmmgr_cnx.so:system/vendor/lib/libmmgr_cnx.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libmmgr_utils.so:system/vendor/lib/libmmgr_utils.so \
    vendor/dell/venue3x40-common/proprietary/vendor/bin/mmgr:system/vendor/bin/mmgr \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libdx_cc7.so:system/vendor/lib/libdx_cc7.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libinterface-provider.so:system/vendor/lib/libinterface-provider.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libmamgr-xmm.so:system/vendor/lib/libmamgr-xmm.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libmcdr.so:system/vendor/lib/libmcdr.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libmodemupdate.so:system/vendor/lib/libmodemupdate.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/librapid-ril-core.so:system/vendor/lib/librapid-ril-core.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/librapid-ril-util.so:system/vendor/lib/librapid-ril-util.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libtcs.so:system/vendor/lib/libtcs.so
