# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/dell/venue3x40-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libIMGegl.so:system/vendor/lib/libIMGegl.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/liboclcompiler.so:system/vendor/lib/liboclcompiler.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libPVROCL.so:system/vendor/lib/libPVROCL.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libsrv_init.so:system/vendor/lib/libsrv_init.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libsrv_um.so:system/vendor/lib/libsrv_um.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libufwriter.so:system/vendor/lib/libufwriter.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libusc.so:system/vendor/lib/libusc.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/egl/libEGL_POWERVR_ROGUE.so:system/vendor/lib/egl/libEGL_POWERVR_ROGUE.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/egl/libGLESv1_CM_POWERVR_ROGUE.so:system/vendor/lib/egl/libGLESv1_CM_POWERVR_ROGUE.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/egl/libGLESv2_POWERVR_ROGUE.so:system/vendor/lib/egl/libGLESv2_POWERVR_ROGUE.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/hw/gralloc.merrifield.so:system/vendor/lib/hw/gralloc.merrifield.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/hw/hwcomposer.merrifield.so:system/vendor/lib/hw/hwcomposer.merrifield.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libhwcwidi.so:system/vendor/lib/libhwcwidi.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libmultidisplay.so:system/vendor/lib/libmultidisplay.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libvpp_setting.so:system/vendor/lib/libvpp_setting.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libmixvbp.so:system/vendor/lib/libmixvbp.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libmixvbp_h264.so:system/vendor/lib/libmixvbp_h264.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libmixvbp_mpeg4.so:system/vendor/lib/libmixvbp_mpeg4.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libmixvbp_vp8.so:system/vendor/lib/libmixvbp_vp8.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/hw/audio.primary.saltbay.so:system/vendor/lib/hw/audio.primary.saltbay.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libauddriver.so:system/vendor/lib/libauddriver.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libaudiohalutils.so:system/vendor/lib/libaudiohalutils.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libaudioresample.so:system/vendor/lib/libaudioresample.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libaudwrapper.so:system/vendor/lib/libaudwrapper.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libdsp.so:system/vendor/lib/libdsp.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libevent-listener.so:system/vendor/lib/libevent-listener.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libgti.so:system/vendor/lib/libgti.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libgtiproxy.so:system/vendor/lib/libgtiproxy.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libgtisrv.so:system/vendor/lib/libgtisrv.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libinterface-provider-lib.so:system/vendor/lib/libinterface-provider-lib.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libparameter.so:system/vendor/lib/libparameter.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libproperty.so:system/vendor/lib/libproperty.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libtinyalsa.so:system/vendor/lib/libtinyalsa.so \
    vendor/dell/venue3x40-common/proprietary/vendor/lib/libutaos.so:system/vendor/lib/libutaos.so \
    vendor/dell/venue3x40-common/proprietary/lib/parameter-framework-plugins/Audio/libdsp-subsystem.so:system/lib/parameter-framework-plugins/Audio/libdsp-subsystem.so \
    vendor/dell/venue3x40-common/proprietary/lib/parameter-framework-plugins/Audio/libimc-subsystem.so:system/lib/parameter-framework-plugins/Audio/libimc-subsystem.so \
    vendor/dell/venue3x40-common/proprietary/lib/parameter-framework-plugins/Audio/libpower-subsystem.so:system/lib/parameter-framework-plugins/Audio/libpower-subsystem.so \
    vendor/dell/venue3x40-common/proprietary/lib/parameter-framework-plugins/Audio/libtinyalsactl-subsystem.so:system/lib/parameter-framework-plugins/Audio/libtinyalsactl-subsystem.so \
    vendor/dell/venue3x40-common/proprietary/lib/parameter-framework-plugins/Audio/libtinyamixer-subsystem.so:system/lib/parameter-framework-plugins/Audio/libtinyamixer-subsystem.so \
    vendor/dell/venue3x40-common/proprietary/lib/parameter-framework-plugins/Audio/libuta-subsystem.so:system/lib/parameter-framework-plugins/Audio/libuta-subsystem.so \
    vendor/dell/venue3x40-common/proprietary/lib/parameter-framework-plugins/Fs/libfs-subsystem.so:system/lib/parameter-framework-plugins/Fs/libfs-subsystem.so \
    vendor/dell/venue3x40-common/proprietary/vendor/firmware/fw_sst_119a.bin:system/vendor/firmware/fw_sst_119a.bin \
    vendor/dell/venue3x40-common/proprietary/vendor/firmware/signed_msvdx_fw_mrfld_b0v1.bin:system/vendor/firmware/signed_msvdx_fw_mrfld_b0v1.bin \
    vendor/dell/venue3x40-common/proprietary/vendor/firmware/topazhp_fw_b0.bin:system/vendor/firmware/topazhp_fw_b0.bin \
    vendor/dell/venue3x40-common/proprietary/vendor/firmware/bcmdhd_aob.cal:system/vendor/firmware/bcmdhd_aob.cal \
    vendor/dell/venue3x40-common/proprietary/vendor/firmware/BCM4335C0_003.001.009.0043.0227.hcd:system/vendor/firmware/BCM4335C0_003.001.009.0043.0227.hcd
